name: test

on:
  push:

jobs:
  test-build:
    strategy:
      fail-fast: false
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: swatinem/rust-cache@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
