name: test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: rust cache
        uses: swatinem/rust-cache@v2
      - name: test
        run: cargo test
